// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var mcpProjects = [
  {
    id: "5",
    title: "The Archive",
    category: "Growth Marketing",
    description: "Kommunikationskoncept f\xF6r NTI Gymnasiet som g\xF6r om bilden av teknikprogrammet \u2013 fr\xE5n n\xE5got smalt till n\xE5got f\xF6r alla med id\xE9er.",
    year: "2026",
    tags: ["Growth Marketing", "Strategy", "Campaign"],
    url: "/projekt/5"
  },
  {
    id: "1",
    title: "Under Your Skin",
    category: "CRO & Analys",
    description: "CRO-analys med fokus p\xE5 att \xF6ka \xE5terkommande kunder och st\xE4rka kundlojalitet.",
    year: "kurs",
    tags: ["CRO & Analys"],
    url: "/projekt/1"
  },
  {
    id: "2",
    title: "Fotografiska",
    category: "Brand Strategy",
    description: "Community-driven brand experience som st\xE4rker Fotografiskas relevans hos framtida m\xE5lgrupper genom deltagande och l\xE5ngsiktig storytelling.",
    year: "2024",
    tags: ["Branding", "Growth", "Strategy"],
    url: "/projekt/2"
  },
  {
    id: "3",
    title: "DryPop",
    category: "Paid Social & Performance Marketing",
    description: "Datadrivet paid social-case med m\xE5lgruppsanalys, kreativ utveckling, A/B-testning och kampanjoptimering i Meta.",
    year: "2024",
    tags: ["Paid Social", "Growth Marketing", "A/B Testing"],
    url: "/projekt/3"
  },
  {
    id: "4",
    title: "Sluta Glo. B\xF6rja Ragga",
    category: "Strategi & Beteendedesign",
    description: "N\xE4r Kexchoklad blev ett verktyg mot ensamhet \u2013 ett strategiskt case om hur en godisprodukt kan bidra till folkh\xE4lsan.",
    year: "2025",
    tags: ["Strategy", "Public Health", "Behavior Design"],
    url: "/projekt/4"
  }
];
var mcpProfile = {
  name: "Sebastian Johansson",
  title: "Growth Marketing Student",
  school: "Berghs School of Communication",
  email: "sebastian.johansson@student.berghs.se",
  bio: "Jag \xE4r growth marketing-student p\xE5 Berghs School of Communication med ett starkt driv att skapa trafik som faktiskt genererar m\xE4tbara resultat. Jag brinner f\xF6r att f\xF6rst\xE5 hela tillv\xE4xtresan \u2013 fr\xE5n f\xF6rsta klick till l\xE5ngsiktig kundrelation \u2013 och motiveras av att testa, analysera och optimera det som verkligen g\xF6r skillnad."
};

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "List the public portfolio case studies, optionally filtered by a search term matching title, category, description or tags.",
  inputSchema: {
    query: z.string().optional().describe("Optional free-text filter, e.g. 'paid social' or 'CRO'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const items = q ? mcpProjects.filter(
      (p) => [p.title, p.category, p.description, ...p.tags].join(" ").toLowerCase().includes(q)
    ) : mcpProjects;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get portfolio project",
  description: "Get the details of one portfolio case study by its id or title.",
  inputSchema: {
    idOrTitle: z2.string().min(1).describe("Project id (e.g. '3') or title (e.g. 'DryPop').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ idOrTitle }) => {
    const needle = idOrTitle.trim().toLowerCase();
    const project = mcpProjects.find(
      (p) => p.id === needle || p.title.toLowerCase() === needle
    );
    if (!project) {
      throw new ToolError(
        `No project matched "${idOrTitle}". Use list_projects to see available projects.`
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get profile and contact",
  description: "Get the portfolio owner's public profile: name, title, school, bio and contact email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mcpProfile, null, 2) }],
    structuredContent: { profile: mcpProfile }
  })
});

// src/lib/mcp/index.ts
var projectRef = "itqjelnmroqphobwslyk";
var mcp_default = defineMcp({
  name: "growth-canvas",
  title: "Growth Canvas",
  version: "0.1.0",
  instructions: "Tools for Sebastian Johansson's growth marketing portfolio. Use `list_projects` to browse case studies, `get_project` for one case study, and `get_profile` for bio and contact details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
